# Generated by Django 6.0.6 on 2026-08-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g. 250g, 500g, 1.0kg', max_length=50),
        ),
    ]
