# Generated by Django 6.0.6 on 2026-08-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.CharField(blank=True, help_text='Alternate/Bangla spellings for search, comma separated. e.g. চাল, chal, rice', max_length=255),
        ),
    ]
