# Generated by Django 6.0.6 on 2026-08-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_search_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_sale_end',
            field=models.DateTimeField(blank=True, help_text='Flash sale kokhon shesh hobe (deadline). is_flash_sale checked thakle eta filup koro.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False, help_text='Check korle eta flash sale e dekhabe'),
        ),
    ]
