# Generated by Django 6.0.6 on 2026-08-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_flash_sale_end_product_is_flash_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Internal name, e.g. 'Sidebar Ad 1'", max_length=150)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField(blank=True, help_text='Optional - click korle kothay jabe')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Choto number age dekhabe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
