# Generated by Django 6.0.6 on 2026-08-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_selling',
            field=models.BooleanField(default=False, help_text="Check korle 'Best Selling Products' section e dekhabe"),
        ),
    ]
