# Generated by Django 6.0.6 on 2026-08-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_is_best_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(choices=[('dhaka', 'Inside Dhaka (৳80)'), ('outside', 'Outside Dhaka (৳140)')], default='dhaka', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=10),
        ),
    ]
