# Generated by Django 6.0.6 on 2026-08-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_delivery_area_order_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_footer',
            field=models.BooleanField(default=False, help_text="Footer er 'Explore Products' e dekhabe"),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Homepage-e top category card e dekhabe'),
        ),
    ]
