# Generated by Django 6.0.6 on 2026-08-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_combo_offer',
            field=models.BooleanField(default=False, help_text='Check korle Combo Offer page e dekhabe'),
        ),
    ]
