# Generated by Django 6.0.6 on 2026-08-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_is_combo_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended size: 400x400px (square, 1:1 ratio). White or transparent background looks best.', null=True, upload_to='categories/'),
        ),
    ]
