# Generated by Django 6.0.6 on 2026-08-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended size: 1000x1000px (square, 1:1 ratio). White/plain background looks best. Higher resolution keeps the zoom-on-hover feature sharp.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Recommended size: 1000x1000px (square, 1:1 ratio), same style as main image.', upload_to='products/gallery/'),
        ),
    ]
